// Auto-generated games list from datasets
// Generated on: 2026-03-10T00:28:22.011Z
// Total games: 222

export interface GameInfo {
  id: string;
  name: string;
  category: string;
  grade: number;
  gradeMin: number;
  gradeMax: number;
  difficulty: string;
  duration: number;
  description: string;
  icon: string;
  tags: string[];
  engine: string;
  datasetPath: string;
}

export const GAMES_LIST: GameInfo[] = [
  {
    id: 'addition-puzzle',
    name: 'Addition Puzzle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Addition Puzzle oyunu',
    icon: '🔢',
    tags: ['math', 'addition'],
    engine: 'PuzzleEngine',
    datasetPath: 'math/addition-puzzle.json',
  },
  {
    id: 'addition-race',
    name: 'Addition Race',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Addition Race oyunu',
    icon: '🔢',
    tags: ['math', 'addition'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/addition-race.json',
  },
  {
    id: 'alien-subtraction',
    name: 'Alien Subtraction',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Alien Subtraction oyunu',
    icon: '🔢',
    tags: ['math', 'alien'],
    engine: 'QuizEngine',
    datasetPath: 'math/alien-subtraction.json',
  },
  {
    id: 'animal-count',
    name: 'Animal Count',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Animal Count oyunu',
    icon: '🔢',
    tags: ['math', 'animal'],
    engine: 'QuizEngine',
    datasetPath: 'math/animal-count.json',
  },
  {
    id: 'apple-collect',
    name: 'Apple Collect',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Apple Collect oyunu',
    icon: '🔢',
    tags: ['math', 'apple'],
    engine: 'QuizEngine',
    datasetPath: 'math/apple-collect.json',
  },
  {
    id: 'area-calculation',
    name: 'Area Calculation',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Area Calculation oyunu',
    icon: '🔢',
    tags: ['math', 'area'],
    engine: 'QuizEngine',
    datasetPath: 'math/area-calculation.json',
  },
  {
    id: 'balloon-count',
    name: 'Balloon Count',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Balloon Count oyunu',
    icon: '🔢',
    tags: ['math', 'balloon'],
    engine: 'QuizEngine',
    datasetPath: 'math/balloon-count.json',
  },
  {
    id: 'balloon-pop',
    name: 'Balloon Pop',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Balloon Pop oyunu',
    icon: '🔢',
    tags: ['math', 'balloon'],
    engine: 'QuizEngine',
    datasetPath: 'math/balloon-pop.json',
  },
  {
    id: 'big-small-race',
    name: 'Big Small Race',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Big Small Race oyunu',
    icon: '🔢',
    tags: ['math', 'big'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/big-small-race.json',
  },
  {
    id: 'boom',
    name: 'Boom',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Boom oyunu',
    icon: '🔢',
    tags: ['math', 'boom'],
    engine: 'QuizEngine',
    datasetPath: 'math/boom.json',
  },
  {
    id: 'careful-eyes',
    name: 'Careful Eyes',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Careful Eyes oyunu',
    icon: '🔢',
    tags: ['math', 'careful'],
    engine: 'QuizEngine',
    datasetPath: 'math/careful-eyes.json',
  },
  {
    id: 'change-calculator',
    name: 'Change Calculator',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Change Calculator oyunu',
    icon: '🔢',
    tags: ['math', 'change'],
    engine: 'QuizEngine',
    datasetPath: 'math/change-calculator.json',
  },
  {
    id: 'clock-reading',
    name: 'Clock Reading',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Clock Reading oyunu',
    icon: '🔢',
    tags: ['math', 'clock'],
    engine: 'QuizEngine',
    datasetPath: 'math/clock-reading.json',
  },
  {
    id: 'color-detective',
    name: 'Color Detective',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Color Detective oyunu',
    icon: '🔢',
    tags: ['math', 'color'],
    engine: 'MatchingEngine',
    datasetPath: 'math/color-detective.json',
  },
  {
    id: 'compare-subtraction',
    name: 'Compare Subtraction',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Compare Subtraction oyunu',
    icon: '🔢',
    tags: ['math', 'compare'],
    engine: 'QuizEngine',
    datasetPath: 'math/compare-subtraction.json',
  },
  {
    id: 'cookie-monster',
    name: 'Cookie Monster',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Cookie Monster oyunu',
    icon: '🔢',
    tags: ['math', 'cookie'],
    engine: 'QuizEngine',
    datasetPath: 'math/cookie-monster.json',
  },
  {
    id: 'correct-order',
    name: 'Correct Order',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Correct Order oyunu',
    icon: '🔢',
    tags: ['math', 'correct'],
    engine: 'SortingEngine',
    datasetPath: 'math/correct-order.json',
  },
  {
    id: 'countdown',
    name: 'Countdown',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Countdown oyunu',
    icon: '🔢',
    tags: ['math', 'countdown'],
    engine: 'QuizEngine',
    datasetPath: 'math/countdown.json',
  },
  {
    id: 'decimal-market',
    name: 'Decimal Market',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Decimal Market oyunu',
    icon: '🔢',
    tags: ['math', 'decimal'],
    engine: 'QuizEngine',
    datasetPath: 'math/decimal-market.json',
  },
  {
    id: 'decimal-sort',
    name: 'Decimal Sort',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Decimal Sort oyunu',
    icon: '🔢',
    tags: ['math', 'decimal'],
    engine: 'SortingEngine',
    datasetPath: 'math/decimal-sort.json',
  },
  {
    id: 'direction-match',
    name: 'Direction Match',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Direction Match oyunu',
    icon: '🔢',
    tags: ['math', 'direction'],
    engine: 'MatchingEngine',
    datasetPath: 'math/direction-match.json',
  },
  {
    id: 'direction',
    name: 'Direction',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Direction oyunu',
    icon: '🔢',
    tags: ['math', 'direction'],
    engine: 'QuizEngine',
    datasetPath: 'math/direction.json',
  },
  {
    id: 'division-hunt',
    name: 'Division Hunt',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Division Hunt oyunu',
    icon: '🔢',
    tags: ['math', 'division'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/division-hunt.json',
  },
  {
    id: 'division-race',
    name: 'Division Race',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Division Race oyunu',
    icon: '🔢',
    tags: ['math', 'division'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/division-race.json',
  },
  {
    id: 'election-tally',
    name: 'Election Tally',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Election Tally oyunu',
    icon: '🔢',
    tags: ['math', 'election'],
    engine: 'QuizEngine',
    datasetPath: 'math/election-tally.json',
  },
  {
    id: 'estimate-jar',
    name: 'Estimate Jar',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Estimate Jar oyunu',
    icon: '🔢',
    tags: ['math', 'estimate'],
    engine: 'QuizEngine',
    datasetPath: 'math/estimate-jar.json',
  },
  {
    id: 'exponent-puzzle',
    name: 'Exponent Puzzle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Exponent Puzzle oyunu',
    icon: '🔢',
    tags: ['math', 'exponent'],
    engine: 'QuizEngine',
    datasetPath: 'math/exponent-puzzle.json',
  },
  {
    id: 'exponent-race',
    name: 'Exponent Race',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Exponent Race oyunu',
    icon: '🔢',
    tags: ['math', 'exponent'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/exponent-race.json',
  },
  {
    id: 'favorite-color-survey',
    name: 'Favorite Color Survey',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Favorite Color Survey oyunu',
    icon: '🔢',
    tags: ['math', 'favorite'],
    engine: 'QuizEngine',
    datasetPath: 'math/favorite-color-survey.json',
  },
  {
    id: 'find-difference',
    name: 'Find Difference',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Find Difference oyunu',
    icon: '🔢',
    tags: ['math', 'find'],
    engine: 'QuizEngine',
    datasetPath: 'math/find-difference.json',
  },
  {
    id: 'fish-addition',
    name: 'Fish Addition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fish Addition oyunu',
    icon: '🔢',
    tags: ['math', 'fish'],
    engine: 'QuizEngine',
    datasetPath: 'math/fish-addition.json',
  },
  {
    id: 'fraction-addition',
    name: 'Fraction Addition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fraction Addition oyunu',
    icon: '🔢',
    tags: ['math', 'fraction'],
    engine: 'QuizEngine',
    datasetPath: 'math/fraction-addition.json',
  },
  {
    id: 'fraction-compare',
    name: 'Fraction Compare',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fraction Compare oyunu',
    icon: '🔢',
    tags: ['math', 'fraction'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/fraction-compare.json',
  },
  {
    id: 'fruit-addition',
    name: 'Fruit Addition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fruit Addition oyunu',
    icon: '🔢',
    tags: ['math', 'fruit'],
    engine: 'QuizEngine',
    datasetPath: 'math/fruit-addition.json',
  },
  {
    id: 'geometric-shape-recognition',
    name: 'Geometric Shape Recognition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Geometric Shape Recognition oyunu',
    icon: '🔢',
    tags: ['math', 'geometric'],
    engine: 'QuizEngine',
    datasetPath: 'math/geometric-shape-recognition.json',
  },
  {
    id: 'graph-completion',
    name: 'Graph Completion',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Graph Completion oyunu',
    icon: '🔢',
    tags: ['math', 'graph'],
    engine: 'DiagramEngine',
    datasetPath: 'math/graph-completion.json',
  },
  {
    id: 'graph-reading',
    name: 'Graph Reading',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Graph Reading oyunu',
    icon: '🔢',
    tags: ['math', 'graph'],
    engine: 'DiagramEngine',
    datasetPath: 'math/graph-reading.json',
  },
  {
    id: 'heaviest-object',
    name: 'Heaviest Object',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Heaviest Object oyunu',
    icon: '🔢',
    tags: ['math', 'heaviest'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/heaviest-object.json',
  },
  {
    id: 'ice-cream-graph',
    name: 'Ice Cream Graph',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Ice Cream Graph oyunu',
    icon: '🔢',
    tags: ['math', 'ice'],
    engine: 'DiagramEngine',
    datasetPath: 'math/ice-cream-graph.json',
  },
  {
    id: 'inside-outside',
    name: 'Inside Outside',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Inside Outside oyunu',
    icon: '🔢',
    tags: ['math', 'inside'],
    engine: 'QuizEngine',
    datasetPath: 'math/inside-outside.json',
  },
  {
    id: 'integer-battle',
    name: 'Integer Battle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Integer Battle oyunu',
    icon: '🔢',
    tags: ['math', 'integer'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/integer-battle.json',
  },
  {
    id: 'left-right-race',
    name: 'Left Right Race',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Left Right Race oyunu',
    icon: '🔢',
    tags: ['math', 'left'],
    engine: 'QuizEngine',
    datasetPath: 'math/left-right-race.json',
  },
  {
    id: 'length-compare',
    name: 'Length Compare',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Length Compare oyunu',
    icon: '🔢',
    tags: ['math', 'length'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/length-compare.json',
  },
  {
    id: 'location-puzzle',
    name: 'Location Puzzle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Location Puzzle oyunu',
    icon: '🔢',
    tags: ['math', 'location'],
    engine: 'MatchingEngine',
    datasetPath: 'math/location-puzzle.json',
  },
  {
    id: 'longest-line',
    name: 'Longest Line',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Longest Line oyunu',
    icon: '🔢',
    tags: ['math', 'longest'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/longest-line.json',
  },
  {
    id: 'longest-object',
    name: 'Longest Object',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Longest Object oyunu',
    icon: '🔢',
    tags: ['math', 'longest'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/longest-object.json',
  },
  {
    id: 'market-basket',
    name: 'Market Basket',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Market Basket oyunu',
    icon: '🔢',
    tags: ['math', 'market'],
    engine: 'QuizEngine',
    datasetPath: 'math/market-basket.json',
  },
  {
    id: 'math-basketball',
    name: 'Math Basketball',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Math Basketball oyunu',
    icon: '🔢',
    tags: ['math', 'math'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/math-basketball.json',
  },
  {
    id: 'maze',
    name: 'Maze',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Maze oyunu',
    icon: '🔢',
    tags: ['math', 'maze'],
    engine: 'SimulationEngine',
    datasetPath: 'math/maze.json',
  },
  {
    id: 'memory-cards',
    name: 'Memory Cards',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Memory Cards oyunu',
    icon: '🔢',
    tags: ['math', 'memory'],
    engine: 'MemoryEngine',
    datasetPath: 'math/memory-cards.json',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Memory Match oyunu',
    icon: '🔢',
    tags: ['math', 'memory'],
    engine: 'MemoryEngine',
    datasetPath: 'math/memory-match.json',
  },
  {
    id: 'missing-number',
    name: 'Missing Number',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Missing Number oyunu',
    icon: '🔢',
    tags: ['math', 'missing'],
    engine: 'QuizEngine',
    datasetPath: 'math/missing-number.json',
  },
  {
    id: 'missing-shape',
    name: 'Missing Shape',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Missing Shape oyunu',
    icon: '🔢',
    tags: ['math', 'missing'],
    engine: 'QuizEngine',
    datasetPath: 'math/missing-shape.json',
  },
  {
    id: 'money-count',
    name: 'Money Count',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Money Count oyunu',
    icon: '🔢',
    tags: ['math', 'money'],
    engine: 'QuizEngine',
    datasetPath: 'math/money-count.json',
  },
  {
    id: 'most-fruit',
    name: 'Most Fruit',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Most Fruit oyunu',
    icon: '🔢',
    tags: ['math', 'most'],
    engine: 'QuizEngine',
    datasetPath: 'math/most-fruit.json',
  },
  {
    id: 'multiplication-battle',
    name: 'Multiplication Battle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Multiplication Battle oyunu',
    icon: '🔢',
    tags: ['math', 'multiplication'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/multiplication-battle.json',
  },
  {
    id: 'multiplication-ninja',
    name: 'Multiplication Ninja',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Multiplication Ninja oyunu',
    icon: '🔢',
    tags: ['math', 'multiplication'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/multiplication-ninja.json',
  },
  {
    id: 'multiplication-table',
    name: 'Multiplication Table',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Multiplication Table oyunu',
    icon: '🔢',
    tags: ['math', 'multiplication'],
    engine: 'QuizEngine',
    datasetPath: 'math/multiplication-table.json',
  },
  {
    id: 'number-building',
    name: 'Number Building',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Building oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-building.json',
  },
  {
    id: 'number-catcher',
    name: 'Number Catcher',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Catcher oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-catcher.json',
  },
  {
    id: 'number-compare',
    name: 'Number Compare',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Compare oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/number-compare.json',
  },
  {
    id: 'number-comparison',
    name: 'Number Comparison',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Comparison oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/number-comparison.json',
  },
  {
    id: 'number-hunt-to100',
    name: 'Number Hunt To100',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Hunt To100 oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-hunt-to100.json',
  },
  {
    id: 'number-line-jump',
    name: 'Number Line Jump',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Line Jump oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-line-jump.json',
  },
  {
    id: 'number-line',
    name: 'Number Line',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Line oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-line.json',
  },
  {
    id: 'number-recognition',
    name: 'Number Recognition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Recognition oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-recognition.json',
  },
  {
    id: 'number-train',
    name: 'Number Train',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Train oyunu',
    icon: '🔢',
    tags: ['math', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'math/number-train.json',
  },
  {
    id: 'pattern-continue',
    name: 'Pattern Continue',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Pattern Continue oyunu',
    icon: '🔢',
    tags: ['math', 'pattern'],
    engine: 'QuizEngine',
    datasetPath: 'math/pattern-continue.json',
  },
  {
    id: 'pattern-puzzle',
    name: 'Pattern Puzzle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Pattern Puzzle oyunu',
    icon: '🔢',
    tags: ['math', 'pattern'],
    engine: 'PuzzleEngine',
    datasetPath: 'math/pattern-puzzle.json',
  },
  {
    id: 'perimeter-calculation',
    name: 'Perimeter Calculation',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Perimeter Calculation oyunu',
    icon: '🔢',
    tags: ['math', 'perimeter'],
    engine: 'QuizEngine',
    datasetPath: 'math/perimeter-calculation.json',
  },
  {
    id: 'pizza-sharing',
    name: 'Pizza Sharing',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Pizza Sharing oyunu',
    icon: '🔢',
    tags: ['math', 'pizza'],
    engine: 'QuizEngine',
    datasetPath: 'math/pizza-sharing.json',
  },
  {
    id: 'place-value',
    name: 'Place Value',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Place Value oyunu',
    icon: '🔢',
    tags: ['math', 'place'],
    engine: 'QuizEngine',
    datasetPath: 'math/place-value.json',
  },
  {
    id: 'problem-solving',
    name: 'Problem Solving',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Problem Solving oyunu',
    icon: '🔢',
    tags: ['math', 'problem'],
    engine: 'QuizEngine',
    datasetPath: 'math/problem-solving.json',
  },
  {
    id: 'race-order',
    name: 'Race Order',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Race Order oyunu',
    icon: '🔢',
    tags: ['math', 'race'],
    engine: 'SortingEngine',
    datasetPath: 'math/race-order.json',
  },
  {
    id: 'rhythmic-run',
    name: 'Rhythmic Run',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Rhythmic Run oyunu',
    icon: '🔢',
    tags: ['math', 'rhythmic'],
    engine: 'QuizEngine',
    datasetPath: 'math/rhythmic-run.json',
  },
  {
    id: 'sequence-pattern',
    name: 'Sequence Pattern',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sequence Pattern oyunu',
    icon: '🔢',
    tags: ['math', 'sequence'],
    engine: 'SortingEngine',
    datasetPath: 'math/sequence-pattern.json',
  },
  {
    id: 'shadow-match',
    name: 'Shadow Match',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shadow Match oyunu',
    icon: '🔢',
    tags: ['math', 'shadow'],
    engine: 'MemoryEngine',
    datasetPath: 'math/shadow-match.json',
  },
  {
    id: 'shape-builder',
    name: 'Shape Builder',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Builder oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-builder.json',
  },
  {
    id: 'shape-count',
    name: 'Shape Count',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Count oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-count.json',
  },
  {
    id: 'shape-detective',
    name: 'Shape Detective',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Detective oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-detective.json',
  },
  {
    id: 'shape-hunt',
    name: 'Shape Hunt',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Hunt oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-hunt.json',
  },
  {
    id: 'shape-hunter',
    name: 'Shape Hunter',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Hunter oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-hunter.json',
  },
  {
    id: 'shape-labyrinth',
    name: 'Shape Labyrinth',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Labyrinth oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'SimulationEngine',
    datasetPath: 'math/shape-labyrinth.json',
  },
  {
    id: 'shape-matching',
    name: 'Shape Matching',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Matching oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'MatchingEngine',
    datasetPath: 'math/shape-matching.json',
  },
  {
    id: 'shape-painting',
    name: 'Shape Painting',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Painting oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'QuizEngine',
    datasetPath: 'math/shape-painting.json',
  },
  {
    id: 'shape-puzzle',
    name: 'Shape Puzzle',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shape Puzzle oyunu',
    icon: '🔢',
    tags: ['math', 'shape'],
    engine: 'PuzzleEngine',
    datasetPath: 'math/shape-puzzle.json',
  },
  {
    id: 'simple-graph',
    name: 'Simple Graph',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Simple Graph oyunu',
    icon: '🔢',
    tags: ['math', 'simple'],
    engine: 'DiagramEngine',
    datasetPath: 'math/simple-graph.json',
  },
  {
    id: 'size-match',
    name: 'Size Match',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Size Match oyunu',
    icon: '🔢',
    tags: ['math', 'size'],
    engine: 'MatchingEngine',
    datasetPath: 'math/size-match.json',
  },
  {
    id: 'size-order',
    name: 'Size Order',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Size Order oyunu',
    icon: '🔢',
    tags: ['math', 'size'],
    engine: 'SortingEngine',
    datasetPath: 'math/size-order.json',
  },
  {
    id: 'skip-counting',
    name: 'Skip Counting',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Skip Counting oyunu',
    icon: '🔢',
    tags: ['math', 'skip'],
    engine: 'QuizEngine',
    datasetPath: 'math/skip-counting.json',
  },
  {
    id: 'space-addition',
    name: 'Space Addition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Space Addition oyunu',
    icon: '🔢',
    tags: ['math', 'space'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/space-addition.json',
  },
  {
    id: 'subtraction-basket',
    name: 'Subtraction Basket',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Subtraction Basket oyunu',
    icon: '🔢',
    tags: ['math', 'subtraction'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/subtraction-basket.json',
  },
  {
    id: 'symmetry',
    name: 'Symmetry',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Symmetry oyunu',
    icon: '🔢',
    tags: ['math', 'symmetry'],
    engine: 'QuizEngine',
    datasetPath: 'math/symmetry.json',
  },
  {
    id: 'temperature',
    name: 'Temperature',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Temperature oyunu',
    icon: '🔢',
    tags: ['math', 'temperature'],
    engine: 'QuizEngine',
    datasetPath: 'math/temperature.json',
  },
  {
    id: 'thousand-hunt',
    name: 'Thousand Hunt',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Thousand Hunt oyunu',
    icon: '🔢',
    tags: ['math', 'thousand'],
    engine: 'QuizEngine',
    datasetPath: 'math/thousand-hunt.json',
  },
  {
    id: 'toy-graph',
    name: 'Toy Graph',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Toy Graph oyunu',
    icon: '🔢',
    tags: ['math', 'toy'],
    engine: 'DiagramEngine',
    datasetPath: 'math/toy-graph.json',
  },
  {
    id: 'toy-lost',
    name: 'Toy Lost',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Toy Lost oyunu',
    icon: '🔢',
    tags: ['math', 'toy'],
    engine: 'QuizEngine',
    datasetPath: 'math/toy-lost.json',
  },
  {
    id: 'two-digit-addition',
    name: 'Two Digit Addition',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Two Digit Addition oyunu',
    icon: '🔢',
    tags: ['math', 'two'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/two-digit-addition.json',
  },
  {
    id: 'two-digit-subtraction',
    name: 'Two Digit Subtraction',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Two Digit Subtraction oyunu',
    icon: '🔢',
    tags: ['math', 'two'],
    engine: 'SpeedQuizEngine',
    datasetPath: 'math/two-digit-subtraction.json',
  },
  {
    id: 'vacation-route',
    name: 'Vacation Route',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Vacation Route oyunu',
    icon: '🔢',
    tags: ['math', 'vacation'],
    engine: 'SimulationEngine',
    datasetPath: 'math/vacation-route.json',
  },
  {
    id: 'weight-compare',
    name: 'Weight Compare',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Weight Compare oyunu',
    icon: '🔢',
    tags: ['math', 'weight'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/weight-compare.json',
  },
  {
    id: 'who-bigger',
    name: 'Who Bigger',
    category: 'math',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Who Bigger oyunu',
    icon: '🔢',
    tags: ['math', 'who'],
    engine: 'ComparisonEngine',
    datasetPath: 'math/who-bigger.json',
  },
  {
    id: 'abalone',
    name: 'Abalone',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Abalone oyunu',
    icon: '🧩',
    tags: ['logic', 'abalone'],
    engine: 'QuizEngine',
    datasetPath: 'logic/abalone.json',
  },
  {
    id: 'akari',
    name: 'Akari',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Akari oyunu',
    icon: '🧩',
    tags: ['logic', 'akari'],
    engine: 'QuizEngine',
    datasetPath: 'logic/akari.json',
  },
  {
    id: 'alphabet-sudoku',
    name: 'Alphabet Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Alphabet Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'alphabet'],
    engine: 'QuizEngine',
    datasetPath: 'logic/alphabet-sudoku.json',
  },
  {
    id: 'anti-king-sudoku',
    name: 'Anti King Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Anti King Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'anti'],
    engine: 'QuizEngine',
    datasetPath: 'logic/anti-king-sudoku.json',
  },
  {
    id: 'anti-knight-sudoku',
    name: 'Anti Knight Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Anti Knight Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'anti'],
    engine: 'QuizEngine',
    datasetPath: 'logic/anti-knight-sudoku.json',
  },
  {
    id: 'arrow-sudoku',
    name: 'Arrow Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Arrow Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'arrow'],
    engine: 'QuizEngine',
    datasetPath: 'logic/arrow-sudoku.json',
  },
  {
    id: 'arukone',
    name: 'Arukone',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Arukone oyunu',
    icon: '🧩',
    tags: ['logic', 'arukone'],
    engine: 'QuizEngine',
    datasetPath: 'logic/arukone.json',
  },
  {
    id: 'backgammon',
    name: 'Backgammon',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Backgammon oyunu',
    icon: '🧩',
    tags: ['logic', 'backgammon'],
    engine: 'QuizEngine',
    datasetPath: 'logic/backgammon.json',
  },
  {
    id: 'battleships',
    name: 'Battleships',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Battleships oyunu',
    icon: '🧩',
    tags: ['logic', 'battleships'],
    engine: 'QuizEngine',
    datasetPath: 'logic/battleships.json',
  },
  {
    id: 'binairo',
    name: 'Binairo',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Binairo oyunu',
    icon: '🧩',
    tags: ['logic', 'binairo'],
    engine: 'QuizEngine',
    datasetPath: 'logic/binairo.json',
  },
  {
    id: 'binoxxo',
    name: 'Binoxxo',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Binoxxo oyunu',
    icon: '🧩',
    tags: ['logic', 'binoxxo'],
    engine: 'QuizEngine',
    datasetPath: 'logic/binoxxo.json',
  },
  {
    id: 'blocked-sudoku',
    name: 'Blocked Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Blocked Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'blocked'],
    engine: 'QuizEngine',
    datasetPath: 'logic/blocked-sudoku.json',
  },
  {
    id: 'blokus-duel',
    name: 'Blokus Duel',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Blokus Duel oyunu',
    icon: '🧩',
    tags: ['logic', 'blokus'],
    engine: 'QuizEngine',
    datasetPath: 'logic/blokus-duel.json',
  },
  {
    id: 'calcudoku',
    name: 'Calcudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Calcudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'calcudoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/calcudoku.json',
  },
  {
    id: 'cave',
    name: 'Cave',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Cave oyunu',
    icon: '🧩',
    tags: ['logic', 'cave'],
    engine: 'QuizEngine',
    datasetPath: 'logic/cave.json',
  },
  {
    id: 'chaos-sudoku',
    name: 'Chaos Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Chaos Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'chaos'],
    engine: 'QuizEngine',
    datasetPath: 'logic/chaos-sudoku.json',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Checkers oyunu',
    icon: '🧩',
    tags: ['logic', 'checkers'],
    engine: 'QuizEngine',
    datasetPath: 'logic/checkers.json',
  },
  {
    id: 'chess',
    name: 'Chess',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Chess oyunu',
    icon: '🧩',
    tags: ['logic', 'chess'],
    engine: 'QuizEngine',
    datasetPath: 'logic/chess.json',
  },
  {
    id: 'color-sudoku',
    name: 'Color Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Color Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'color'],
    engine: 'QuizEngine',
    datasetPath: 'logic/color-sudoku.json',
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Connect Four oyunu',
    icon: '🧩',
    tags: ['logic', 'connect'],
    engine: 'QuizEngine',
    datasetPath: 'logic/connect-four.json',
  },
  {
    id: 'consecutive-sudoku',
    name: 'Consecutive Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Consecutive Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'consecutive'],
    engine: 'QuizEngine',
    datasetPath: 'logic/consecutive-sudoku.json',
  },
  {
    id: 'cross-logic',
    name: 'Cross Logic',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Cross Logic oyunu',
    icon: '🧩',
    tags: ['logic', 'cross'],
    engine: 'QuizEngine',
    datasetPath: 'logic/cross-logic.json',
  },
  {
    id: 'cross-sums',
    name: 'Cross Sums',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Cross Sums oyunu',
    icon: '🧩',
    tags: ['logic', 'cross'],
    engine: 'QuizEngine',
    datasetPath: 'logic/cross-sums.json',
  },
  {
    id: 'diagonal-sudoku',
    name: 'Diagonal Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Diagonal Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'diagonal'],
    engine: 'QuizEngine',
    datasetPath: 'logic/diagonal-sudoku.json',
  },
  {
    id: 'domino-sudoku',
    name: 'Domino Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Domino Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'domino'],
    engine: 'QuizEngine',
    datasetPath: 'logic/domino-sudoku.json',
  },
  {
    id: 'domino',
    name: 'Domino',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Domino oyunu',
    icon: '🧩',
    tags: ['logic', 'domino'],
    engine: 'QuizEngine',
    datasetPath: 'logic/domino.json',
  },
  {
    id: 'dominosa',
    name: 'Dominosa',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Dominosa oyunu',
    icon: '🧩',
    tags: ['logic', 'dominosa'],
    engine: 'QuizEngine',
    datasetPath: 'logic/dominosa.json',
  },
  {
    id: 'dot-sudoku',
    name: 'Dot Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Dot Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'dot'],
    engine: 'QuizEngine',
    datasetPath: 'logic/dot-sudoku.json',
  },
  {
    id: 'dots-and-boxes',
    name: 'Dots And Boxes',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Dots And Boxes oyunu',
    icon: '🧩',
    tags: ['logic', 'dots'],
    engine: 'QuizEngine',
    datasetPath: 'logic/dots-and-boxes.json',
  },
  {
    id: 'einstein-riddle',
    name: 'Einstein Riddle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Einstein Riddle oyunu',
    icon: '🧩',
    tags: ['logic', 'einstein'],
    engine: 'QuizEngine',
    datasetPath: 'logic/einstein-riddle.json',
  },
  {
    id: 'even-odd-sudoku',
    name: 'Even Odd Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Even Odd Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'even'],
    engine: 'QuizEngine',
    datasetPath: 'logic/even-odd-sudoku.json',
  },
  {
    id: 'fanorona',
    name: 'Fanorona',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fanorona oyunu',
    icon: '🧩',
    tags: ['logic', 'fanorona'],
    engine: 'QuizEngine',
    datasetPath: 'logic/fanorona.json',
  },
  {
    id: 'fillomino',
    name: 'Fillomino',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Fillomino oyunu',
    icon: '🧩',
    tags: ['logic', 'fillomino'],
    engine: 'QuizEngine',
    datasetPath: 'logic/fillomino.json',
  },
  {
    id: 'futoshiki',
    name: 'Futoshiki',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Futoshiki oyunu',
    icon: '🧩',
    tags: ['logic', 'futoshiki'],
    engine: 'QuizEngine',
    datasetPath: 'logic/futoshiki.json',
  },
  {
    id: 'go',
    name: 'Go',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Go oyunu',
    icon: '🧩',
    tags: ['logic', 'go'],
    engine: 'QuizEngine',
    datasetPath: 'logic/go.json',
  },
  {
    id: 'gomoku',
    name: 'Gomoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Gomoku oyunu',
    icon: '🧩',
    tags: ['logic', 'gomoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/gomoku.json',
  },
  {
    id: 'greater-than-killer-sudoku',
    name: 'Greater Than Killer Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Greater Than Killer Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'greater'],
    engine: 'QuizEngine',
    datasetPath: 'logic/greater-than-killer-sudoku.json',
  },
  {
    id: 'greater-than-sudoku',
    name: 'Greater Than Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Greater Than Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'greater'],
    engine: 'QuizEngine',
    datasetPath: 'logic/greater-than-sudoku.json',
  },
  {
    id: 'griddlers',
    name: 'Griddlers',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Griddlers oyunu',
    icon: '🧩',
    tags: ['logic', 'griddlers'],
    engine: 'QuizEngine',
    datasetPath: 'logic/griddlers.json',
  },
  {
    id: 'halma',
    name: 'Halma',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Halma oyunu',
    icon: '🧩',
    tags: ['logic', 'halma'],
    engine: 'QuizEngine',
    datasetPath: 'logic/halma.json',
  },
  {
    id: 'hashi',
    name: 'Hashi',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hashi oyunu',
    icon: '🧩',
    tags: ['logic', 'hashi'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hashi.json',
  },
  {
    id: 'hex-sudoku',
    name: 'Hex Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hex Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'hex'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hex-sudoku.json',
  },
  {
    id: 'hidato',
    name: 'Hidato',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hidato oyunu',
    icon: '🧩',
    tags: ['logic', 'hidato'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hidato.json',
  },
  {
    id: 'hitori',
    name: 'Hitori',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hitori oyunu',
    icon: '🧩',
    tags: ['logic', 'hitori'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hitori.json',
  },
  {
    id: 'hive',
    name: 'Hive',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hive oyunu',
    icon: '🧩',
    tags: ['logic', 'hive'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hive.json',
  },
  {
    id: 'hyper-sudoku',
    name: 'Hyper Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Hyper Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'hyper'],
    engine: 'QuizEngine',
    datasetPath: 'logic/hyper-sudoku.json',
  },
  {
    id: 'irregular-sudoku',
    name: 'Irregular Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Irregular Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'irregular'],
    engine: 'QuizEngine',
    datasetPath: 'logic/irregular-sudoku.json',
  },
  {
    id: 'jenga',
    name: 'Jenga',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Jenga oyunu',
    icon: '🧩',
    tags: ['logic', 'jenga'],
    engine: 'QuizEngine',
    datasetPath: 'logic/jenga.json',
  },
  {
    id: 'jigsaw-sudoku',
    name: 'Jigsaw Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Jigsaw Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'jigsaw'],
    engine: 'QuizEngine',
    datasetPath: 'logic/jigsaw-sudoku.json',
  },
  {
    id: 'kakuro',
    name: 'Kakuro',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Kakuro oyunu',
    icon: '🧩',
    tags: ['logic', 'kakuro'],
    engine: 'QuizEngine',
    datasetPath: 'logic/kakuro.json',
  },
  {
    id: 'kalah',
    name: 'Kalah',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Kalah oyunu',
    icon: '🧩',
    tags: ['logic', 'kalah'],
    engine: 'QuizEngine',
    datasetPath: 'logic/kalah.json',
  },
  {
    id: 'ken-ken',
    name: 'Ken Ken',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Ken Ken oyunu',
    icon: '🧩',
    tags: ['logic', 'ken'],
    engine: 'QuizEngine',
    datasetPath: 'logic/ken-ken.json',
  },
  {
    id: 'killer-sudoku',
    name: 'Killer Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Killer Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'killer'],
    engine: 'QuizEngine',
    datasetPath: 'logic/killer-sudoku.json',
  },
  {
    id: 'kropki-sudoku',
    name: 'Kropki Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Kropki Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'kropki'],
    engine: 'QuizEngine',
    datasetPath: 'logic/kropki-sudoku.json',
  },
  {
    id: 'kuromasu',
    name: 'Kuromasu',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Kuromasu oyunu',
    icon: '🧩',
    tags: ['logic', 'kuromasu'],
    engine: 'QuizEngine',
    datasetPath: 'logic/kuromasu.json',
  },
  {
    id: 'latin-squares',
    name: 'Latin Squares',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Latin Squares oyunu',
    icon: '🧩',
    tags: ['logic', 'latin'],
    engine: 'QuizEngine',
    datasetPath: 'logic/latin-squares.json',
  },
  {
    id: 'light-and-shadow',
    name: 'Light And Shadow',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Light And Shadow oyunu',
    icon: '🧩',
    tags: ['logic', 'light'],
    engine: 'QuizEngine',
    datasetPath: 'logic/light-and-shadow.json',
  },
  {
    id: 'lits',
    name: 'Lits',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Lits oyunu',
    icon: '🧩',
    tags: ['logic', 'lits'],
    engine: 'QuizEngine',
    datasetPath: 'logic/lits.json',
  },
  {
    id: 'little-killer-sudoku',
    name: 'Little Killer Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Little Killer Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'little'],
    engine: 'QuizEngine',
    datasetPath: 'logic/little-killer-sudoku.json',
  },
  {
    id: 'logic-grid-puzzle',
    name: 'Logic Grid Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Logic Grid Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'logic'],
    engine: 'QuizEngine',
    datasetPath: 'logic/logic-grid-puzzle.json',
  },
  {
    id: 'loop-puzzle',
    name: 'Loop Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Loop Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'loop'],
    engine: 'QuizEngine',
    datasetPath: 'logic/loop-puzzle.json',
  },
  {
    id: 'magnets',
    name: 'Magnets',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Magnets oyunu',
    icon: '🧩',
    tags: ['logic', 'magnets'],
    engine: 'QuizEngine',
    datasetPath: 'logic/magnets.json',
  },
  {
    id: 'mancala',
    name: 'Mancala',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Mancala oyunu',
    icon: '🧩',
    tags: ['logic', 'mancala'],
    engine: 'QuizEngine',
    datasetPath: 'logic/mancala.json',
  },
  {
    id: 'mastermind',
    name: 'Mastermind',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Mastermind oyunu',
    icon: '🧩',
    tags: ['logic', 'mastermind'],
    engine: 'QuizEngine',
    datasetPath: 'logic/mastermind.json',
  },
  {
    id: 'masyu',
    name: 'Masyu',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Masyu oyunu',
    icon: '🧩',
    tags: ['logic', 'masyu'],
    engine: 'QuizEngine',
    datasetPath: 'logic/masyu.json',
  },
  {
    id: 'mathdoku',
    name: 'Mathdoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Mathdoku oyunu',
    icon: '🧩',
    tags: ['logic', 'mathdoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/mathdoku.json',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Minesweeper oyunu',
    icon: '🧩',
    tags: ['logic', 'minesweeper'],
    engine: 'QuizEngine',
    datasetPath: 'logic/minesweeper.json',
  },
  {
    id: 'mini-sudoku',
    name: 'Mini Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Mini Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'mini'],
    engine: 'QuizEngine',
    datasetPath: 'logic/mini-sudoku.json',
  },
  {
    id: 'mosaic-puzzle',
    name: 'Mosaic Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Mosaic Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'mosaic'],
    engine: 'QuizEngine',
    datasetPath: 'logic/mosaic-puzzle.json',
  },
  {
    id: 'nim',
    name: 'Nim',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Nim oyunu',
    icon: '🧩',
    tags: ['logic', 'nim'],
    engine: 'QuizEngine',
    datasetPath: 'logic/nim.json',
  },
  {
    id: 'nine-mens-morris',
    name: 'Nine Mens Morris',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Nine Mens Morris oyunu',
    icon: '🧩',
    tags: ['logic', 'nine'],
    engine: 'QuizEngine',
    datasetPath: 'logic/nine-mens-morris.json',
  },
  {
    id: 'non-consecutive-sudoku',
    name: 'Non Consecutive Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Non Consecutive Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'non'],
    engine: 'QuizEngine',
    datasetPath: 'logic/non-consecutive-sudoku.json',
  },
  {
    id: 'nonogram',
    name: 'Nonogram',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Nonogram oyunu',
    icon: '🧩',
    tags: ['logic', 'nonogram'],
    engine: 'QuizEngine',
    datasetPath: 'logic/nonogram.json',
  },
  {
    id: 'number-snake',
    name: 'Number Snake',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Number Snake oyunu',
    icon: '🧩',
    tags: ['logic', 'number'],
    engine: 'QuizEngine',
    datasetPath: 'logic/number-snake.json',
  },
  {
    id: 'numberlink',
    name: 'Numberlink',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Numberlink oyunu',
    icon: '🧩',
    tags: ['logic', 'numberlink'],
    engine: 'QuizEngine',
    datasetPath: 'logic/numberlink.json',
  },
  {
    id: 'numbrix',
    name: 'Numbrix',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Numbrix oyunu',
    icon: '🧩',
    tags: ['logic', 'numbrix'],
    engine: 'QuizEngine',
    datasetPath: 'logic/numbrix.json',
  },
  {
    id: 'nurikabe',
    name: 'Nurikabe',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Nurikabe oyunu',
    icon: '🧩',
    tags: ['logic', 'nurikabe'],
    engine: 'QuizEngine',
    datasetPath: 'logic/nurikabe.json',
  },
  {
    id: 'nurimisaki',
    name: 'Nurimisaki',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Nurimisaki oyunu',
    icon: '🧩',
    tags: ['logic', 'nurimisaki'],
    engine: 'QuizEngine',
    datasetPath: 'logic/nurimisaki.json',
  },
  {
    id: 'onitama',
    name: 'Onitama',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Onitama oyunu',
    icon: '🧩',
    tags: ['logic', 'onitama'],
    engine: 'QuizEngine',
    datasetPath: 'logic/onitama.json',
  },
  {
    id: 'pente',
    name: 'Pente',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Pente oyunu',
    icon: '🧩',
    tags: ['logic', 'pente'],
    engine: 'QuizEngine',
    datasetPath: 'logic/pente.json',
  },
  {
    id: 'pentomino-puzzle',
    name: 'Pentomino Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Pentomino Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'pentomino'],
    engine: 'QuizEngine',
    datasetPath: 'logic/pentomino-puzzle.json',
  },
  {
    id: 'picross',
    name: 'Picross',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Picross oyunu',
    icon: '🧩',
    tags: ['logic', 'picross'],
    engine: 'QuizEngine',
    datasetPath: 'logic/picross.json',
  },
  {
    id: 'polyomino-puzzle',
    name: 'Polyomino Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Polyomino Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'polyomino'],
    engine: 'QuizEngine',
    datasetPath: 'logic/polyomino-puzzle.json',
  },
  {
    id: 'quad-sudoku',
    name: 'Quad Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Quad Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'quad'],
    engine: 'QuizEngine',
    datasetPath: 'logic/quad-sudoku.json',
  },
  {
    id: 'quoridor',
    name: 'Quoridor',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Quoridor oyunu',
    icon: '🧩',
    tags: ['logic', 'quoridor'],
    engine: 'QuizEngine',
    datasetPath: 'logic/quoridor.json',
  },
  {
    id: 'reversi',
    name: 'Reversi',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Reversi oyunu',
    icon: '🧩',
    tags: ['logic', 'reversi'],
    engine: 'QuizEngine',
    datasetPath: 'logic/reversi.json',
  },
  {
    id: 'ripple-effect',
    name: 'Ripple Effect',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Ripple Effect oyunu',
    icon: '🧩',
    tags: ['logic', 'ripple'],
    engine: 'QuizEngine',
    datasetPath: 'logic/ripple-effect.json',
  },
  {
    id: 'samurai-killer-sudoku',
    name: 'Samurai Killer Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Samurai Killer Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'samurai'],
    engine: 'QuizEngine',
    datasetPath: 'logic/samurai-killer-sudoku.json',
  },
  {
    id: 'samurai-sudoku',
    name: 'Samurai Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Samurai Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'samurai'],
    engine: 'QuizEngine',
    datasetPath: 'logic/samurai-sudoku.json',
  },
  {
    id: 'sandwich-sudoku',
    name: 'Sandwich Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sandwich Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'sandwich'],
    engine: 'QuizEngine',
    datasetPath: 'logic/sandwich-sudoku.json',
  },
  {
    id: 'santorini',
    name: 'Santorini',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Santorini oyunu',
    icon: '🧩',
    tags: ['logic', 'santorini'],
    engine: 'QuizEngine',
    datasetPath: 'logic/santorini.json',
  },
  {
    id: 'shikaku',
    name: 'Shikaku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shikaku oyunu',
    icon: '🧩',
    tags: ['logic', 'shikaku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/shikaku.json',
  },
  {
    id: 'shogi',
    name: 'Shogi',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Shogi oyunu',
    icon: '🧩',
    tags: ['logic', 'shogi'],
    engine: 'QuizEngine',
    datasetPath: 'logic/shogi.json',
  },
  {
    id: 'skyscrapers',
    name: 'Skyscrapers',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Skyscrapers oyunu',
    icon: '🧩',
    tags: ['logic', 'skyscrapers'],
    engine: 'QuizEngine',
    datasetPath: 'logic/skyscrapers.json',
  },
  {
    id: 'slant',
    name: 'Slant',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Slant oyunu',
    icon: '🧩',
    tags: ['logic', 'slant'],
    engine: 'QuizEngine',
    datasetPath: 'logic/slant.json',
  },
  {
    id: 'slitherlink',
    name: 'Slitherlink',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Slitherlink oyunu',
    icon: '🧩',
    tags: ['logic', 'slitherlink'],
    engine: 'QuizEngine',
    datasetPath: 'logic/slitherlink.json',
  },
  {
    id: 'sos',
    name: 'Sos',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sos oyunu',
    icon: '🧩',
    tags: ['logic', 'sos'],
    engine: 'QuizEngine',
    datasetPath: 'logic/sos.json',
  },
  {
    id: 'spiral-galaxies',
    name: 'Spiral Galaxies',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Spiral Galaxies oyunu',
    icon: '🧩',
    tags: ['logic', 'spiral'],
    engine: 'QuizEngine',
    datasetPath: 'logic/spiral-galaxies.json',
  },
  {
    id: 'star-battle',
    name: 'Star Battle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Star Battle oyunu',
    icon: '🧩',
    tags: ['logic', 'star'],
    engine: 'QuizEngine',
    datasetPath: 'logic/star-battle.json',
  },
  {
    id: 'strimko',
    name: 'Strimko',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Strimko oyunu',
    icon: '🧩',
    tags: ['logic', 'strimko'],
    engine: 'QuizEngine',
    datasetPath: 'logic/strimko.json',
  },
  {
    id: 'sudoku-x',
    name: 'Sudoku X',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sudoku X oyunu',
    icon: '🧩',
    tags: ['logic', 'sudoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/sudoku-x.json',
  },
  {
    id: 'sudoku-y',
    name: 'Sudoku Y',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sudoku Y oyunu',
    icon: '🧩',
    tags: ['logic', 'sudoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/sudoku-y.json',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'sudoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/sudoku.json',
  },
  {
    id: 'suguru',
    name: 'Suguru',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Suguru oyunu',
    icon: '🧩',
    tags: ['logic', 'suguru'],
    engine: 'QuizEngine',
    datasetPath: 'logic/suguru.json',
  },
  {
    id: 'tak',
    name: 'Tak',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tak oyunu',
    icon: '🧩',
    tags: ['logic', 'tak'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tak.json',
  },
  {
    id: 'takuzu',
    name: 'Takuzu',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Takuzu oyunu',
    icon: '🧩',
    tags: ['logic', 'takuzu'],
    engine: 'QuizEngine',
    datasetPath: 'logic/takuzu.json',
  },
  {
    id: 'tapa',
    name: 'Tapa',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tapa oyunu',
    icon: '🧩',
    tags: ['logic', 'tapa'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tapa.json',
  },
  {
    id: 'tectonics',
    name: 'Tectonics',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tectonics oyunu',
    icon: '🧩',
    tags: ['logic', 'tectonics'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tectonics.json',
  },
  {
    id: 'tents-trees',
    name: 'Tents Trees',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tents Trees oyunu',
    icon: '🧩',
    tags: ['logic', 'tents'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tents-trees.json',
  },
  {
    id: 'thermo-sudoku',
    name: 'Thermo Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Thermo Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'thermo'],
    engine: 'QuizEngine',
    datasetPath: 'logic/thermo-sudoku.json',
  },
  {
    id: 'tic-tac-toe',
    name: 'Tic Tac Toe',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tic Tac Toe oyunu',
    icon: '🧩',
    tags: ['logic', 'tic'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tic-tac-toe.json',
  },
  {
    id: 'tower-puzzle',
    name: 'Tower Puzzle',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Tower Puzzle oyunu',
    icon: '🧩',
    tags: ['logic', 'tower'],
    engine: 'QuizEngine',
    datasetPath: 'logic/tower-puzzle.json',
  },
  {
    id: 'train-tracks',
    name: 'Train Tracks',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Train Tracks oyunu',
    icon: '🧩',
    tags: ['logic', 'train'],
    engine: 'QuizEngine',
    datasetPath: 'logic/train-tracks.json',
  },
  {
    id: 'triple-sudoku',
    name: 'Triple Sudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Triple Sudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'triple'],
    engine: 'QuizEngine',
    datasetPath: 'logic/triple-sudoku.json',
  },
  {
    id: 'two-not-touch',
    name: 'Two Not Touch',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Two Not Touch oyunu',
    icon: '🧩',
    tags: ['logic', 'two'],
    engine: 'QuizEngine',
    datasetPath: 'logic/two-not-touch.json',
  },
  {
    id: 'windoku',
    name: 'Windoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Windoku oyunu',
    icon: '🧩',
    tags: ['logic', 'windoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/windoku.json',
  },
  {
    id: 'wordoku',
    name: 'Wordoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Wordoku oyunu',
    icon: '🧩',
    tags: ['logic', 'wordoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/wordoku.json',
  },
  {
    id: 'xiangqi',
    name: 'Xiangqi',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Xiangqi oyunu',
    icon: '🧩',
    tags: ['logic', 'xiangqi'],
    engine: 'QuizEngine',
    datasetPath: 'logic/xiangqi.json',
  },
  {
    id: 'xvsudoku',
    name: 'Xvsudoku',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Xvsudoku oyunu',
    icon: '🧩',
    tags: ['logic', 'xvsudoku'],
    engine: 'QuizEngine',
    datasetPath: 'logic/xvsudoku.json',
  },
  {
    id: 'yajilin',
    name: 'Yajilin',
    category: 'logic',
    grade: 3,
    gradeMin: 3,
    gradeMax: 3,
    difficulty: 'medium',
    duration: 300,
    description: 'Yajilin oyunu',
    icon: '🧩',
    tags: ['logic', 'yajilin'],
    engine: 'QuizEngine',
    datasetPath: 'logic/yajilin.json',
  },
];
