export enum Difficulty {
  VERY_EASY = 'VERY_EASY',
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  VERY_HARD = 'VERY_HARD',
}

export enum GameMode {
  HOME = 'HOME',
  // Fast Reading
  FAST_READING_MEASUREMENT = 'FAST_READING_MEASUREMENT',
  FAST_READING_EYE_FLOW = 'FAST_READING_EYE_FLOW',
  FAST_READING_FOCUS_TRAINING = 'FAST_READING_FOCUS_TRAINING',
  FAST_READING_FOCUS = 'FAST_READING_FOCUS',
  
  // Focus
  FOCUS_POMODORO = 'FOCUS_POMODORO',
  FOCUS_ATTENTION = 'FOCUS_ATTENTION',
  FOCUS_MEMORY_CARDS = 'FOCUS_MEMORY_CARDS',
  FOCUS_COLOR_MATCH = 'FOCUS_COLOR_MATCH',
  FOCUS_NUMBER_SEQUENCE = 'FOCUS_NUMBER_SEQUENCE',
  FOCUS_BREATHING = 'FOCUS_BREATHING',
  FOCUS_MAZE = 'FOCUS_MAZE',
  
  // Learning
  LEARNING_COMPREHENSION = 'LEARNING_COMPREHENSION',
  LEARNING_FLASHCARD = 'LEARNING_FLASHCARD',
  LEARNING_PARAPHRASE = 'LEARNING_PARAPHRASE',
  MEMORY_MIND_MAP = 'MEMORY_MIND_MAP',
  MEMORY_MNEMONIC = 'MEMORY_MNEMONIC',
  
  // Language
  LANGUAGE_DAILY_WORDS = 'LANGUAGE_DAILY_WORDS',
  LANGUAGE_SYNONYMS = 'LANGUAGE_SYNONYMS',
  LANGUAGE_ANTONYMS = 'LANGUAGE_ANTONYMS',
  LANGUAGE_IDIOMS = 'LANGUAGE_IDIOMS',
  LANGUAGE_PROVERBS = 'LANGUAGE_PROVERBS',
  LANGUAGE_METAPHORS = 'LANGUAGE_METAPHORS',
  LANGUAGE_WORD_GAME = 'LANGUAGE_WORD_GAME',
  LANGUAGE_AI_QUIZ = 'LANGUAGE_AI_QUIZ',
  LANGUAGE_SIM = 'LANGUAGE_SIM',
  
  // Two Player
  TWO_PLAYER_TIC_TAC_TOE = 'TWO_PLAYER_TIC_TAC_TOE',
  TWO_PLAYER_CONNECT_FOUR = 'TWO_PLAYER_CONNECT_FOUR',
  TWO_PLAYER_SOS = 'TWO_PLAYER_SOS',
  TWO_PLAYER_DOTS_BOXES = 'TWO_PLAYER_DOTS_BOXES',
  TWO_PLAYER_MANCALA = 'TWO_PLAYER_MANCALA',
  TWO_PLAYER_CHESS = 'TWO_PLAYER_CHESS',
  TWO_PLAYER_CHECKERS = 'TWO_PLAYER_CHECKERS',
  TWO_PLAYER_REVERSI = 'TWO_PLAYER_REVERSI',
  TWO_PLAYER_NIM = 'TWO_PLAYER_NIM',
}

export interface UserStats {
  fastReadingWpm?: number;
  focusScore?: number;
  learningScore?: number;
}

export interface GameResult {
  stars: number;
  score: number;
  timeSpent: number;
  mistakes: number;
}
